# Generated by Django 5.0.2 on 2024-02-18 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('subject', models.CharField(max_length=25)),
                ('description', models.CharField(default='Default description', max_length=25)),
                ('test', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=25)),
                ('lesson', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='step_lesson', to='DMK.lesson')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='steps',
            field=models.ManyToManyField(related_name='lesson_steps', to='DMK.step'),
        ),
    ]
